# version: '3'
# services:
#   app:
#     build:
#       context: .
#     ports:
#       - "4444:4444"
#     volumes:
#       - .:/app
#   tests:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     volumes:
#       - .:/app
#     depends_on:
#       - app
#     environment:
#       - NODE_ENV=ci
version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - chrome
    environment:
      - NODE_ENV=production
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
