name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME $DOCKER_PASSWORD --password-stdin
      # - name: Build Docker image
      #   run: docker build -t my-docker-image:latest .
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
            node-version: 16.x
      - name: Install dependencies
        run: npm ci
      # - name: Build project
      #   run: npm run build
      - name: Run tests
        # run: docker run my-docker-image:latest npm run wdio
        run: docker-compose up --build
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint