name: CI

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - "4445:4444"

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Setup Node.js
        uses: actions/setup-node@v2.5.2
        with:
            node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build docker image
        run: docker build -t my-image .
      - name: Run tests in docker
        run: docker run --rm my-image npm run test:ui
      - name: Stop Docker container
        if: always()
        run: docker ps -a -q --filter ancestor=my-image:latest
    env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: ./
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      - run: sonar-scanner -Dsonar.projectKey=${{secrets.SONARQUBE_PROJECT_KEY}}  -Dsonar.sources=./

  # quality-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run quality check
  #       run: npm run quality-check